name: Build SQL (DacPac)
on:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Cache NuGet Packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.sqlproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore
        run: dotnet restore ForgeDB.slnx

      - name: Build
        run: dotnet build ForgeDB.slnx --configuration Release --no-restore

      # - name: Install SqlPackage
      #   uses: microsoft/sqlpackage-action@v2

      - name: Generate Deployment Script
        run: >
          sqlpackage
          /Action:Script
          /SourceFile:"path\to\ForgeDB.dacpac"
          /TargetConnectionString:"${{ secrets.DB_CONNECTION_STRING }}"
          /OutputPath:"Deploy.sql"
          
      - name: Generate Drift Report
        run: >
          sqlpackage
            /Action:DriftReport
            /SourceConnectionString:"${{ secrets.DB_CONNECTION_STRING }}"
            /OutputPath:"DriftReport.xml"

      - name: Upload Deployment Script
        uses: actions/upload-artifact@v4
        with:
          name: deploy-script
          path: Deploy.sql

      - name: Upload Drift Report
        uses: actions/upload-artifact@v4
        with:
          name: drift-report
          path: DriftReport.xml

      - name: Upload DACPAC
        uses: actions/upload-artifact@v4
        with:
          name: dacpac
          path: '**/*.dacpac'
